title: Seth Holloway
author:
  name: Seth Holloway
    #email: sethholloway@sethholloway.com
description: >
  Seth Holloway PhD, is a technology leader who tries to improve 
  everyday. Sometimes, he succeeeds.

minima:
  date_format: "%b %-d, %Y"
  show_excerpts: true # set to true to show excerpts on the homepage
  social_links:
  - title: Seth Holloway GitHub
    icon: github
    url: "https://github.com/smholloway"
  - title: Seth Holloway on Google Scholar
    icon: google-scholar
    url: "https://scholar.google.com/citations?user=IeZbwRsAAAAJ"
  - title: Seth Holloway on keybase
    icon: keybase
    url: "https://keybase.io/sethholloway"
  - title: Seth Holloway LinkedIn
    icon: linkedin
    url: "https://www.linkedin.com/in/sethholloway"
  - title: Seth Holloway stackoverflow
    icon: stack-overflow
    url: "https://stackoverflow.com/users/553403/smholloway"
  - title: Seth Holloway X (formerly Twitter)
    icon: x-twitter
    url: "https://twitter.com/sethholloway"
  - title: Seth Holloway RSS
    icon: rss
    url: "https://sethholloway.com/feed.xml"

show_excerpts: true # set to true to show excerpts on the homepage

permalink: :title/

# Build settings
baseurl: /
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-redirect-from

google_analytics: UA-7555904-1
